### ISSUE TITLE
method from_url

### ISSUE THREAD

**Issue by kikrahau** [tinify/tinify-ruby#1]
Hi,

I would like to ask, if there is a possibility to get an image from an url instead from the file system. 
Like:
```ruby
source = Tinify.from_url('http://www.example.com/pic.jpg')
``` 
Is there an easy way to get to that solution with the current API/Library?

Thanks!

**Comment by rolftimmermans** [comment]
At the moment we don't have any built-in methods to do this. But it's pretty easy to get the URL contents with the HTTPClient which is included with the library;

```
require "tinify"

Tinify.key = "..." # Your API key

image = HTTPClient.get_content("http://www.example.com/pic.jpg")
Tinify.from_buffer(image).to_file("optimized-pic.jpg")
```

**Comment by rolftimmermans** [comment]
We'll definitely also consider whether this is something we want to add to all Tinify API clients. Thanks for your suggestion!
