### ISSUE TITLE
Combine compressing and saving to s3 to one request.

### ISSUE THREAD

**Issue by trantorLiu** [tinify/tinify-ruby#3]
When doing this
```ruby
source = Tinify.from_file("unoptimized.jpg")
source.store(
  service: "s3",
  aws_access_key_id: "AKIAIOSFODNN7EXAMPLE",
  aws_secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
  region: "us-west-1",
  path: "example-bucket/my-images/optimized.jpg"
)
```
Two requests will be issues one by one. But base on the [docs for HTTP](https://tinypng.com/developers/reference#saving-to-amazon-s3), the two steps can be combined to one request by providing store info while posting the file.

**Comment by rolftimmermans** [comment]
Thanks for opening this issue.

To clarify, there will always be two requests:
1) Upload & optimize the original
2) Download/store the optimized image & optionally resize based on the uploaded original

This is true for the raw HTTP API as well as the Ruby client.

Are you running into any issues?

**Comment by trantorLiu** [comment]
I see. Thank you! It works fine. I just want to reduce API calls for better performance. It would be great if I can compress and store to s3 in one step.
